# formulas - formulario de AP Calculus para TI-Nspire CX II CAS
# Adrian. Solo formulas y tips, cero calculos.
# Se abre desde ap() (opcion 12) o corriendo este programa.
# Contenido redactado y verificado matematicamente (2026-09-14).

TEMAS = [
    ('Limites y continuidad', [
        '-- limites notables --',
        'lim x->0 sin(x)/x = 1',
        'lim x->0 (1-cos x)/x = 0',
        'lim x->inf (1+1/x)^x = e',
        'lim x->0 (1+x)^(1/x) = e',
        'TIP: x->0: sin(kx)/(mx) -> k/m',
        '',
        '-- limites laterales --',
        'lim existe si lados coinciden:',
        'lim x->a- f = lim x->a+ f = L',
        'si difieren, lim NO existe',
        'TIP: en |x| y tramos revisa lados',
        '',
        "-- l'hopital --",
        'Solo formas 0/0 o inf/inf',
        "f,g derivables, g'!=0 cerca de a",
        "lim f(x)/g(x) = lim f'(x)/g'(x)",
        'TIP: verifica la forma ANTES',
        'TIP: deriva num y den APARTE,',
        'no es la regla del cociente',
        "TIP: escribe 'forma 0/0' en FRQ",
        '',
        '-- continuidad en x=a --',
        '1) f(a) existe',
        '2) lim x->a f(x) existe',
        '3) lim x->a f(x) = f(a)',
        'TIP: cita las 3 en un FRQ',
        '',
        '-- discontinuidades --',
        'Removible: lim existe, pero',
        'f(a) != lim o f(a) no existe',
        'Salto: lim izq != lim der',
        '(ambos laterales finitos)',
        'Infinita: asintota vertical',
        'TIP: removible = hueco arreglable',
        '',
        '-- asintotas (racionales) --',
        'Vertical: den=0 y num!=0',
        'TIP: num=den=0: simplifica;',
        'queda hueco o AV segun factor',
        'Horizontal: compara grados',
        'grado num < den: y = 0',
        'iguales: y = razon coef lider',
        'grado num > den: no hay AH',
        'TIP: AH = lim x->+-inf f(x)',
        '',
        '-- IVT valor intermedio --',
        'f continua en [a,b], k entre',
        'f(a) y f(b) => existe c en',
        '(a,b) con f(c) = k',
        "TIP: FRQ: di 'f es continua'",
        'TIP: y da f(a), f(b) con signos',
        '',
        '-- teorema del sandwich --',
        'g <= f <= h cerca de a y',
        'lim g = lim h = L => lim f = L',
        'TIP: x^2 sin(1/x) -> 0 si x->0',
    ]),
    ('Derivadas: reglas y tabla', [
        '-- definicion de derivada --',
        "f'(x) = lim h->0 [f(x+h)-f(x)]/h",
        "f'(c) = lim x->c [f(x)-f(c)]/(x-c)",
        'TIP: ese limite = derivada disfrazada',
        '',
        '-- derivable y continua --',
        'derivable => continua (no al reves)',
        '|x| es continua pero no derivable en 0',
        "no hay f'(c) si hay: esquina, cuspide,",
        'tangente vertical o discontinuidad',
        '',
        '-- reglas basicas --',
        "d/dx[c]=0, d/dx[c*f]=c*f', (f+g)'=f'+g'",
        'potencia: d/dx[x^n] = n*x^(n-1)',
        "producto: (f*g)' = f'*g + f*g'",
        "cociente: (f/g)' = (f'*g - f*g')/g^2",
        "TIP: en cociente f' va primero arriba",
        '',
        '-- regla de la cadena --',
        "d/dx[f(g(x))] = f'(g(x)) * g'(x)",
        "TIP: no olvides multiplicar por g'(x)",
        '',
        '-- tabla de derivadas --',
        'd/dx[e^x] = e^x',
        'd/dx[a^x] = a^x * ln(a)',
        'd/dx[ln(x)] = 1/x',
        'd/dx[log_a(x)] = 1/(x*ln(a))',
        'd/dx[sin(x)] = cos(x)',
        'd/dx[cos(x)] = -sin(x)',
        'd/dx[tan(x)] = sec(x)^2',
        'd/dx[sec(x)] = sec(x)*tan(x)',
        'd/dx[csc(x)] = -csc(x)*cot(x)',
        'd/dx[cot(x)] = -csc(x)^2',
        "TIP: las 'co' llevan signo negativo",
        '',
        '-- inversas trigonometricas --',
        'd/dx[arcsin(x)] = 1/sqrt(1-x^2)',
        'd/dx[arccos(x)] = -1/sqrt(1-x^2)',
        'd/dx[arctan(x)] = 1/(1+x^2)',
        '',
        '-- derivacion implicita --',
        '1) deriva ambos lados respecto a x',
        '2) terminos con y: usa cadena (dy/dx)',
        '3) agrupa terminos con dy/dx',
        '4) factoriza dy/dx y despeja',
        'TIP: con punto dado, sustituye (x,y)',
        'tras derivar (nunca antes de derivar)',
        '',
        '-- derivada de la inversa --',
        "(f^-1)'(a) = 1/f'(f^-1(a))",
        "requiere f'(f^-1(a)) != 0",
        "TIP: halla b con f(b)=a; usa 1/f'(b)",
    ]),
    ('Aplicaciones de la derivada', [
        '-- tangente y normal --',
        "tangente: y = f(a) + f'(a)(x-a)",
        "normal: pendiente = -1/f'(a)",
        "requiere f'(a) != 0",
        '',
        '-- linearizacion --',
        "L(x) = f(a) + f'(a)(x-a)",
        'TIP: concava abajo -> L sobreestima',
        'TIP: concava arriba -> L subestima',
        '',
        '-- MVT y Rolle --',
        'f continua en [a,b], derivable (a,b)',
        "-> c en (a,b): f'(c)=(f(b)-f(a))/(b-a)",
        "Rolle: ademas f(a)=f(b) -> f'(c)=0",
        '',
        '-- EVT --',
        'f continua en [a,b] -> max y min abs',
        '',
        '-- criticos y extremos abs --',
        "critico: f'(c)=0 o f'(c) no existe",
        'c debe estar en el dominio de f',
        'abs: evalua f en criticos y bordes',
        '',
        '-- test 1a derivada --',
        "f' de + a - en c -> max relativo",
        "f' de - a + en c -> min relativo",
        '',
        '-- test 2a derivada --',
        "f'(c)=0 y f''(c)<0 -> max rel",
        "f'(c)=0 y f''(c)>0 -> min rel",
        "TIP: f''(c)=0 no concluye, usa f'",
        '',
        '-- concavidad e inflexion --',
        "f''>0 concava arriba, f''<0 abajo",
        "inflexion: f'' cambia de signo",
        "TIP: f''=0 no basta sin cambio",
        '',
        '-- movimiento rectilineo --',
        "v = x'(t), a = v'(t), rapidez = |v|",
        'rapidez sube si v*a>0, baja si v*a<0',
        'derecha si v>0, izquierda si v<0',
        '',
        '-- related rates --',
        '1 ecuacion 2 deriva d/dt 3 sustituye',
        'TIP: sustituye numeros AL FINAL',
        '',
        '-- optimizacion --',
        "1 objetivo 2 restriccion 3 f'=0",
        'TIP: verifica max/min y checa bordes',
        '',
        '-- frases AP --',
        "max rel en c: f' cambia de + a -",
        "min rel en c: f' cambia de - a +",
        'max abs: compara f en candidatos',
        'TIP: justifica con signos, no grafica',
    ]),
    ('Integrales y Teorema Fundamental', [
        '-- teorema fundamental parte 1 --',
        'd/dx Int[a,x] f(t)dt = f(x)',
        "d/dx Int[a,g(x)] f(t)dt = f(g(x))g'(x)",
        '(requiere f continua)',
        'TIP: si la variable esta abajo,',
        'invierte limites y cambia signo',
        '',
        '-- teorema fundamental parte 2 --',
        'Int[a,b] f(x)dx = F(b) - F(a)',
        'F es cualquier antiderivada de f',
        '(requiere f continua en [a,b])',
        '',
        '-- antiderivadas basicas --',
        'Int x^n dx = x^(n+1)/(n+1)+C, n!=-1',
        'Int 1/x dx = ln|x| + C',
        'Int e^x dx = e^x + C',
        'Int cos x dx = sin x + C',
        'Int sin x dx = -cos x + C',
        'Int sec^2 x dx = tan x + C',
        'Int sec x tan x dx = sec x + C',
        'Int 1/(1+x^2) dx = arctan x + C',
        'Int 1/sqrt(1-x^2) dx = arcsin x + C',
        'TIP: no olvides +C en indefinidas,',
        'vale puntos en el FRQ',
        '',
        '-- u-sustitucion --',
        "elige u = parte interna, du = u'dx",
        "Int f(g(x))g'(x)dx = Int f(u)du",
        'TIP: en definidas cambia limites:',
        'x=a -> u=g(a), x=b -> u=g(b)',
        'y ya no regreses a x',
        '',
        '-- propiedades --',
        'Int[a,b] f = -Int[b,a] f',
        'Int[a,b] f + Int[b,c] f = Int[a,c] f',
        'Int (f+g) = Int f + Int g',
        'Int c*f = c*Int f',
        '',
        '-- sumas de riemann --',
        'S = Sum f(x_i)*dx, dx = (b-a)/n',
        'x_i: extremo izq, der o pto medio',
        'trapecio = (izq + der)/2',
        'TIP: f creciente =>',
        'izq subestima, der sobreestima',
        'f decreciente => al reves',
        'TIP: concava arriba => trapecio',
        'sobreestima, pto medio subestima',
        'concava abajo => al reves',
        '',
        '-- valor promedio --',
        'f_prom = 1/(b-a) * Int[a,b] f(x)dx',
        'TIP: no es (f(a)+f(b))/2',
    ]),
    ('Aplicaciones de integral y EDO', [
        '-- area entre curvas --',
        'A = Int[a,b] (arriba - abajo) dx',
        'A = Int[c,d] (der - izq) dy',
        'TIP: si se cruzan, parte la integral',
        'TIP: cruce: resuelve f = g en la calc',
        '',
        '-- volumen: discos y arandelas --',
        'disco: V = pi Int[a,b] R^2 dx',
        'arandela: V = pi Int[a,b] (R^2 - r^2) dx',
        'R y r se miden DESDE el eje de giro',
        'TIP: gira en y=k: R = |curva - k|',
        'TIP: (R^2 - r^2) != (R - r)^2',
        '',
        '-- secciones transversales --',
        'V = Int[a,b] A(x) dx, s = dist curvas',
        'cuadrado: A = s^2',
        'semicirculo: A = (pi/8) s^2',
        'tri equilatero: A = (sqrt(3)/4) s^2',
        'tri rect isosceles: A = (1/2) s^2',
        'TIP: sin pi salvo semicirculo',
        '',
        '-- movimiento --',
        'pos final = pos inicial + Int[a,b] v dt',
        'desplazamiento = Int[a,b] v dt',
        'distancia = Int[a,b] |v| dt',
        'TIP: distancia >= |desplazamiento|',
        '',
        '-- acumulacion --',
        'cantidad = inicial + Int[a,b] razon dt',
        'TIP: entra - sale = razon neta',
        'TIP: max/min: razon neta = 0 o extremos',
        'TIP: max si razon pasa de + a -',
        '',
        '-- EDO separables --',
        '1) separa: g(y) dy = f(x) dx',
        '2) integra ambos lados',
        '3) +C ANTES de despejar y',
        '4) usa condicion inicial para C',
        '5) despeja y si lo piden',
        'TIP: e^C se vuelve una constante A',
        '',
        '-- crecimiento exponencial --',
        'dy/dt = ky => y = C e^(kt)',
        'C = y(0), valor inicial',
        "TIP: 'proporcional a y' => dy/dt = ky",
        '',
        '-- campos de pendientes --',
        'cada segmento tiene pendiente dy/dx',
        'TIP: busca donde dy/dx = 0 (horiz)',
        'TIP: checa signo de dy/dx por region',
        'TIP: solo x en la EDO: columnas iguales',
        'TIP: solo y en la EDO: filas iguales',
    ]),
    ('BC: Tecnicas, Parametricas, Polares', [
        '-- integracion por partes --',
        'Int u dv = uv - Int v du',
        'LIATE: Log, InvTrig, Alg, Trig, Exp',
        'TIP: u = la mas alta en LIATE',
        'TIP: dv debe ser facil de integrar',
        '',
        '-- fracciones parciales --',
        'P/((x-a)(x-b)) = A/(x-a)+B/(x-b)',
        'TIP: evalua x=a y x=b para A y B',
        'TIP: si grado arriba >= abajo, divide',
        '',
        '-- integrales impropias --',
        'Int[a,inf] f dx =',
        '  lim b->inf Int[a,b] f dx',
        'converge si el limite es finito',
        'TIP: escribe el limite en el examen',
        '',
        '-- longitud de arco --',
        "L = Int[a,b] sqrt(1+(f'(x))^2) dx",
        '',
        '-- ecuacion logistica --',
        'dP/dt = kP(1 - P/L)',
        'lim t->inf P = L (capacidad)',
        'crecimiento max en P = L/2',
        'TIP: en P=L/2, dP/dt = kL/4',
        '',
        '-- metodo de euler --',
        'y_sig = y + h*F(x,y)',
        'x_sig = x + h',
        'h = paso, F(x,y) = dy/dx',
        'TIP: haz tabla: x, y, dy/dx, y_sig',
        '',
        '-- parametricas --',
        'dy/dx = (dy/dt)/(dx/dt)',
        'd2y/dx2 = d/dt(dy/dx) / (dx/dt)',
        'L = Int[a,b]',
        '  sqrt((dx/dt)^2+(dy/dt)^2) dt',
        'TIP: tang horiz: dy/dt=0, dx/dt!=0',
        'TIP: tang vert: dx/dt=0, dy/dt!=0',
        '',
        '-- movimiento vectorial --',
        "v(t) = <x'(t), y'(t)>",
        "a(t) = <x''(t), y''(t)>",
        "rapidez = sqrt((x')^2+(y')^2)",
        'distancia = Int[a,b] rapidez dt',
        '',
        '-- polares --',
        'x = r cos(t), y = r sin(t)',
        'Area = (1/2) Int[a,b] r^2 dt',
        'TIP: limites del area: resuelve r=0',
        'TIP: checa interseccion de curvas',
    ]),
    ('BC: Series', [
        '-- serie geometrica --',
        'Sum a*r^n = a/(1-r) si |r| < 1',
        'TIP: a = 1er termino de la serie',
        'TIP: si |r| >= 1 diverge',
        '',
        '-- test del n-esimo termino --',
        'si lim a_n != 0 (o no existe) => div',
        'TIP: lim a_n = 0 NO concluye nada',
        '',
        '-- p-series: Sum 1/n^p --',
        'conv si p > 1; div si p <= 1',
        'TIP: armonica Sum 1/n (p=1) div',
        '',
        '-- comparacion --',
        'Directa, 0 <= a_n <= b_n:',
        'b_n conv=>a_n conv; a_n div=>b_n div',
        'Lim: a_n/b_n->L, 0<L<inf: mismo fin',
        '',
        '-- test de la integral --',
        'f pos, cont, decrec, a_n = f(n):',
        'Sum a_n conv <=> Int[1,inf] f dx conv',
        '',
        '-- serie alternante --',
        'Sum(-1)^n a_n, a_n > 0:',
        'conv si a_n decrece y lim a_n = 0',
        'error: |S - S_n| <= a_(n+1)',
        'TIP: cota = 1er termino omitido',
        '',
        '-- test de la razon --',
        'L = lim |a_(n+1)/a_n|',
        'L<1 conv abs; L>1 div; L=1 no dice',
        'TIP: usalo para radio de conv R',
        '',
        '-- conv absoluta vs condicional --',
        'abs: Sum |a_n| conv => Sum a_n conv',
        'cond: Sum a_n conv, Sum |a_n| div',
        '',
        '-- Taylor en c (Maclaurin: c=0) --',
        'Sum n=0..inf f^(n)(c)(x-c)^n/n!',
        'TIP: coef de (x-c)^n = f^(n)(c)/n!',
        'TIP: polinomio P_n = hasta grado n',
        '',
        '-- Maclaurin (e^x,sin,cos: todo x) --',
        'e^x = Sum x^n/n!',
        'sin x = Sum(-1)^n x^(2n+1)/(2n+1)!',
        'cos x = Sum(-1)^n x^(2n)/(2n)!',
        '1/(1-x) = Sum x^n, |x| < 1',
        'ln(1+x) = Sum(-1)^(n+1) x^n/n, n>=1',
        'ln(1+x): -1 < x <= 1',
        'arctan x = Sum(-1)^n x^(2n+1)/(2n+1)',
        'arctan: -1 <= x <= 1',
        '',
        '-- error de Lagrange --',
        '|R_n| <= M|x-c|^(n+1)/(n+1)!',
        'M = max |f^(n+1)| entre c y x',
        '',
        '-- intervalo de convergencia --',
        'razon da |x-c| < R; checa extremos',
        'TIP: cada extremo aparte, otro test',
    ]),
    ('AP CALC: TIPS DE EXAMEN', [
        '-- decimales y redondeo --',
        'TIP: respuestas con 3 decimales min',
        'TIP: redondea o trunca, ambos ok',
        'TIP: NUNCA redondees pasos intermedios',
        'TIP: guarda valores completos en calc',
        '',
        '-- justifica con calculo --',
        "TIP: nunca 'se ve en la grafica'",
        "max rel: f'(x) cambia de + a -",
        "min rel: f'(x) cambia de - a +",
        "concava arriba: f''(x) > 0",
        "pto inflexion: f'' cambia de signo",
        'MVT: cita f continua en [a,b]',
        'MVT: y derivable en (a,b)',
        'IVT: cita f continua en [a,b]',
        'IVT: y k entre f(a) y f(b)',
        '',
        '-- unidades y contexto --',
        'TIP: pon unidades si hay contexto',
        "TIP: interpreta: 'razon a la que...'",
        'TIP: di que, cuando y unidades',
        '',
        '-- vel vs rapidez, desp vs dist --',
        'velocidad = v(t), tiene signo',
        'rapidez = |v(t)|',
        'desplazamiento = Int[a,b] v(t) dt',
        'distancia = Int[a,b] |v(t)| dt',
        'TIP: lee cual piden, trampa clasica',
        '',
        '-- seccion con calculadora --',
        'TIP: integra/deriva numerico, ok',
        'TIP: sin pasos algebraicos, PERO',
        'TIP: ESCRIBE la integral o ecuacion',
        'TIP: planteada antes del numero',
        '',
        '-- no simplifiques --',
        'TIP: dejar 3/7 + e^2 esta bien',
        '',
        '-- manejo de tiempo --',
        'MCQ A: 30 preg/60 min, ~2 min c/u',
        'MCQ B: 15 preg/45 min, ~3 min c/u',
        'FRQ: 6 problemas, ~15 min c/u',
        'calc solo en MCQ B y FRQ parte A',
        'TIP: si te atoras, marca y sigue',
        '',
        '-- lee EXACTO que piden --',
        'TIP: trapecio? justifica? intervalo?',
        'TIP: subraya los verbos clave',
        '',
        '-- puntos FRQ --',
        'TIP: dan puntos por partes',
        'TIP: intenta TODOS los incisos',
        'TIP: aunque no salga el (a)',
    ]),
]


def formulario():
    while True:
        print("")
        print("== FORMULARIO AP CALC ==")
        for i, (t, _) in enumerate(TEMAS):
            print("{} {}".format(i + 1, t))
        print("0 salir")
        s = input("? ").strip()
        if s == "0" or s == "":
            return
        try:
            n = int(s)
        except ValueError:
            continue
        if 1 <= n <= len(TEMAS):
            _fo_muestra(TEMAS[n - 1])


_FO_ANCHO = 36   # caracteres por renglon del shell de la Nspire
_FO_ALTO = 8     # renglones por pantalla antes de pausar


def _fo_muestra(tema):
    """Pagina contando los renglones que se doblan en la pantalla."""
    titulo, lineas = tema
    print("")
    print("== " + titulo + " ==")
    c = 1
    for ln in lineas:
        alto = (len(ln) - 1) // _FO_ANCHO + 1 if ln else 1
        if c + alto > _FO_ALTO:
            if input("-- enter=mas, q=menu --").strip() == "q":
                return
            c = 0
        print(ln)
        c += alto
    input("-- fin, enter --")


# --- autorun ---
if __name__ == "__main__":
    formulario()
